### ISSUE TITLE
How to read the barcodes?

### ISSUE THREAD

**Issue by mayurpande** [WhyNotHugo/python-barcode#1]
This looks like what I need. However if I wanted to scan this barcode and read into my program to see what it is, is this possible?

**Comment by danielkauffman** [comment]
For scanning barcodes, you'll need a barcode scanner (hardware).  Generally, barcode scanners have a visible or audible indicator to let the user know that the scan is complete, decode the scanned information, and the scanner API provides the decoded information to your application.  This library is for generating barcodes, not reading them.

**Comment by WhyNotHugo** [comment]
Much like @danielkauffman said, this is only for generating barcodes, not reading them.

A lot of cheap USB-scanners work like a sort of keyboard: you scan a barcode, and they simulate key presses to type the parsed code.

I'm sure other libraries can do barcode parsing -- there's definitely applications online that let you parse barcode images.
