### ISSUE TITLE
Code39 and Code128 Missing kwarg Default

### ISSUE THREAD

**Issue by JoshMayberry** [WhyNotHugo/python-barcode#10]
For barcodes that are not code39 and code128, the user is able to call the render function without specifying 'writer_options'. This is because that argument is set equal to None by default in 'base.py'

However, in 'codex.py', both classes Code39 and Code128 override render(), but do not set 'writer_options' equal to None by default.

Proposed Change: Use `def render(self, writer_options=None, text=None):` instead of `def render(self, writer_options, text=None):` for Code39 and Code128.

**Comment by WhyNotHugo** [comment]
Good catch, thanks!
