### ISSUE TITLE
Ubuntu install

### ISSUE THREAD

**Issue by hackmac27** [WhyNotHugo/python-barcode#105]
Can't install. Get an error:

File "usr/local/lib/python2.7/dist-packages/pip/_internal/cli/main.py", line 60
sys.stderr.write(f"ERROR: {exc}")

SyntaxError: invalid syntax

**Comment by WhyNotHugo** [comment]
Python 2 has reached its end of life a long time ago and is no longer supported.

You'll need a Python >= 3.6.
