### ISSUE TITLE
version 0.13 incompatible with python 3.5

### ISSUE THREAD

**Issue by yoch** [WhyNotHugo/python-barcode#107]
Because type hints aren't supported on class attributes. Working from python 3.6.

Here is my traceback :
```
    from barcode.codex import Code39
  File "/home/galien/easyprep/env/lib/python3.5/site-packages/barcode/__init__.py", line 11, in <module>
    from barcode.codex import Code128
  File "/home/galien/easyprep/env/lib/python3.5/site-packages/barcode/codex.py", line 5, in <module>
    from barcode.base import Barcode
  File "/home/galien/easyprep/env/lib/python3.5/site-packages/barcode/base.py", line 4, in <module>
    from barcode.writer import SVGWriter
  File "/home/galien/easyprep/env/lib/python3.5/site-packages/barcode/writer.py", line 335
    format: str
          ^
SyntaxError: invalid syntax
```

**Comment by WhyNotHugo** [comment]
Python 3.5 no longer has any support.

Python 3.6 and 3.7 are the oldest versions with _any_ support, and only receive security fixes.
See [here](https://en.wikipedia.org/wiki/History_of_Python#Table_of_versions) for more details.

If you're stuck on al older version of Python, I'd suggest you avoid upgrading python-barcode to 0.13.

**Comment by WhyNotHugo** [comment]
Oh, this is mentioned in the README but not the changelog, I'll address the later when I have a few minutes.

**Comment by yoch** [comment]
Ok, then you should add `python_requires=">=3.6"` to your setup.py.
This will prevent pip from installing th latest version on older versions.

https://packaging.python.org/guides/distributing-packages-using-setuptools/#python-requires
