### ISSUE TITLE
trying to use library on rpi

### ISSUE THREAD

**Issue by djoii** [WhyNotHugo/python-barcode#109]
I keep running into several seemingly version dependent issues trying to get code written and working with python3 on a ubuntu machine running on python3 on a rpi. First it was several syntax errors related to property type assignment. ie format: str vs format.type=str, but I fix that and now im getting: 'module' object has no attribute 'PathLike' and similar others. 

Has anyone used this library on an rpi before?

**Comment by marcoaaguiar** [comment]
What is the Python version running in your rpi? Pathlike is "new" in Python 3.6 ([docs](https://docs.python.org/3/library/os.html#os.PathLike)) That might be the issue
