### ISSUE TITLE
EAN-13/GTIN-13 barcodes don't contain grouping

### ISSUE THREAD

**Issue by jfinkhaeuser** [WhyNotHugo/python-barcode#11]
According to the specs I've found, GTIN-13/EAN-13 barcodes must contain the grouping most commonly found on printed barcodes, i.e. the first character is outside of the code area, and the remainder is in two groups with elongated bars separating the groups.

Is there any support for this planned? How about the '>' mark for silent areas?

**Comment by WhyNotHugo** [comment]
> According to the specs I've found

Can you link those? It'd really make looking into it easier.

**Comment by jfinkhaeuser** [comment]
After this time, I'll have to google them :D But let me see what I can find.

**Comment by jfinkhaeuser** [comment]
Here: https://www.gs1.org/sites/default/files/docs/barcodes/GS1_General_Specifications.pdf

Section 5.2.2.1 lists the components of an EAN-13 barcode. The elongated bars are referred to as a guard bar pattern.

HTH

**Comment by jfinkhaeuser** [comment]
Accidentally closed.

**Comment by WhyNotHugo** [comment]
This has been fix in master (thanks @Governa!).

I've done some testing on this and it seems to look fine. I'm going to wait a couple of days before releasing a new version in case anyone has further feedback on it.
