### ISSUE TITLE
TypeError running # Example with PNG in usage guide

### ISSUE THREAD

**Issue by DannyDannyDanny** [WhyNotHugo/python-barcode#12]
I'm running Python 3.5.5. A subsection of the usage guide:
```python
import barcode
from barcode.writer import ImageWriter
EAN = barcode.get_barcode_class('code128')
ean = EAN(u'5901234123457', writer=ImageWriter())
```

 ...gives me the following error:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-67-21778fac1b87> in <module>()
----> 1 ean = EAN(u'5901234123457', writer=ImageWriter())

TypeError: 'NoneType' object is not callable
```
Am I doing something wrong?

**Comment by JWarmenhoven** [comment]
It runs when using  `writer=ImageWriter`, but then an SVG image is created. Not a PNG.

**Comment by code807** [comment]
Ok so I finally figured out what this is. ImageWriter tries to import Image, which used to come from PIL, (Python Image Library) which is no longer supported or included with Python. This issue can be remedied by installing [Pillow](https://pypi.org/project/Pillow/), which is a working fork of PIL. 

Side note: Pretty sure this makes Pillow a dependency for python-barcode.

**Comment by WhyNotHugo** [comment]
Pillow is already listed as an optional dependency for exporting images.

--
Hugo Osvaldo Barrera

**Comment by code807** [comment]
I see it now. Maybe PIL should be specified or linked as pillow? PIL is no longer entirely accurate, since only a fork works.

**Comment by WhyNotHugo** [comment]
Pillow is listed as an optional dependency, not PIL.
Some docs still have outdated PIL references, so I've updated these.

**Comment by wellmonwu** [comment]
pls ,update PIL to Pillow for python3, and add the Pillow dependency to be must when pip install python-barcode

**Comment by WhyNotHugo** [comment]
@wellmonwu Please see previous comments. PIL has never been listed as a dependency; only pillow. Also, python2 has never supported, only python3.

Finally, pillow is only required if you're exporting image files (eg: not svg), so it will always be listed as an optional dependency, not  a"must".

**Comment by DannyDannyDanny** [comment]
Perhaps this could explicitly be stated in the error.

**Comment by wellmonwu** [comment]
cannot agreed more . this is for newer ------------------ 原始邮件 ------------------
发件人: "Daniel Thoren"<notifications@github.com>
发送时间: 2019年7月22日(星期一) 晚上11:38
收件人: "WhyNotHugo/python-barcode"<python-barcode@noreply.github.com>;
抄送: "wellmon"<wellmon_wu@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [WhyNotHugo/python-barcode] TypeError running # Example with PNGin usage guide (#12)



Perhaps this could explicitly be stated in the error.
 
&mdash;
