### ISSUE TITLE
how to render barcode with options

### ISSUE THREAD

**Issue by HeroadZ** [WhyNotHugo/python-barcode#132]
Thank you for this excellent library!
it's possible to save barcode with options. But options is ignored for render function.
Is there any way to render the barcode with the options?
The background is that I want to generate barcode by string and return by API.
The example code:
```py
def get(self, request, *args, **kwargs):
        s = request.GET.get('s')
        writer = barcode.writer.SVGWriter()
        writer.set_options({xxx}) //not working
        _code = barcode.get('code128', s, writer=writer)
        return HttpResponse(_code.render(), content_type="image/svg+xml")
```

**Comment by avmakesh** [comment]
Use the option with .write() or .render()
eg: 
 stream = BytesIO()
 code = str(bill_id)

 render_options = {
        "module_width": 0.1,
        "module_height": 7,
        "quiet_zone": 0.1,
        "write_text": False,
        "text_distance": 2,
    }

    ITF(code, writer=writer1, narrow=2, wide=5).write(stream, render_options )
or 

 render_options = {
        "module_width": 0.07,
        "module_height": 3,
        "write_text": "",
        "quiet_zone": 0.1,
    }
    barC = barcode.get_barcode_class("itf")
    bar_ = barC(code, writer=ImageWriter())
    b = bar_.render(render_options)
    # b.save("test8.jpg") #image 
    b.save(stream, format="PNG") #save to buff

See the render_options dict to understand how it should be used !
Hope this will help !
