### ISSUE TITLE
`barcode.PROVIDED_BARCODES` vs. Supported Formats in docs

### ISSUE THREAD

**Issue by SeaDude** [WhyNotHugo/python-barcode#154]
Hello,

Thank you for all the hard work you put into this library. I'm curious between the barcodes shown in `barcode.PROVIDED_BARCODES` and the list of Supported Formats in the [docs](https://python-barcode.readthedocs.io/en/stable/supported-formats.html). 

- Are there more Supported Formats then those lined out in the docs? 
- Or are the codes listed in `PROVIDED_BARCODES` derivatives of other codes?

**Example:**

- I don't see `codabar`, `ean13-guard`, `gs1`, etc. in the Supported Formats section of the docs.

```
['codabar', 'code128', 'code39', 'ean', 'ean13', 'ean13-guard', 'ean14', 'ean8', 'ean8-guard', 'gs1', 'gs1_128', 'gtin', 'isbn', 'isbn10', 'isbn13', 'issn', 'itf', 'jan', 'nw-7', 'pzn', 'upc', 'upca']
```

**Comment by WhyNotHugo** [comment]
There should be no different between `barcode.PROVIDED_BARCODES` vs. Supported Formats. Some are missing from the docs as an oversight.

I guess that when generating the docs, we should read `barcode.PROVIDED_BARCODES`, and include all the barcodes listed there programatically.
