### ISSUE TITLE
Better way to validate barcode data?

### ISSUE THREAD

**Issue by SeaDude** [WhyNotHugo/python-barcode#155]
Hello,

Should I validate barcode data manually or is there a simple way using the library?

**Example:**
- `ean13` codes must be 12 numeric digits or `jan` codes must start with 45 or 49. 
- I only found this out by testing the
  - `barcode.ean.EuropeanArticleNumber13(barcode_data, writer=SVGWriter()).write(barcode_bytes)` and
  - `barcode.ean.JapanArticleNumber(barcode_data, writer=SVGWriter()).write(barcode_bytes)` functions

- **Is there a "cheat sheet" of all the barcode requirements so I can roll-my-own validation?** OR
- **Is there a better way to validate using the library itself?**

Thank you!

**Comment by WhyNotHugo** [comment]
Some barcodes validate the provided input. For example: https://github.com/WhyNotHugo/python-barcode/blob/962754e0de08821bd20e980aa79e5f692023b6c6/barcode/ean.py#L44-L54

Some have validation, others don't. If you have a snippet of code to validate any barcode that's missing a validation, I'm happy to include that.
