### ISSUE TITLE
Import Errors

### ISSUE THREAD

**Issue by Cielquan** [WhyNotHugo/python-barcode#161]
I try to use this library, but strangely the import won't work and I am clueless. Other third-party libs from PyPI are working flawlessly.

OS: Win 10
Python Versions: 3.10.5 | 3.8.10
Shell: (Git-)Bash

## Reproduction

Create venv, activate it, update pip, install python-barcode. Then follow examples below
```shell
$ py -3.8 -m venv .venv && . .venv/Scripts/activate && python -m pip install -U pip && pip install python-barcode
```

### Example 1

Create `barcode.py` file with content:
```python
from barcode import EAN
```

Run file and see error:
```shell
$ python barcode.py
Traceback (most recent call last):
  File "barcode.py", line 1, in <module>
    from barcode import EAN
  File "C:\Users\riedelc\projects\zebra-printer\barcode.py", line 1, in <module>
    from barcode import EAN
ImportError: cannot import name 'EAN' from partially initialized module 'barcode' (most likely due to a circular import) (C:\Users\riedelc\projects\zebra-printer\barcode.py)
```

### Example 2

Create `barcode.py` file with content:
```python
from barcode import codex
```

Run file and see error:
```shell
$ python barcode.py 
Traceback (most recent call last):
  File "barcode.py", line 1, in <module>
    from barcode import codex
  File "C:\Users\riedelc\projects\zebra-printer\barcode.py", line 1, in <module>
    from barcode import codex
ImportError: cannot import name 'codex' from partially initialized module 'barcode' (most likely due to a circular import) (C:\Users\riedelc\projects\zebra-printer\barcode.py)
```

### Example 3

Create `barcode.py` file with content:
```python
from barcode.codex import EAN
```

Run file and see error:
```shell
$ python barcode.py
Traceback (most recent call last):
  File "barcode.py", line 1, in <module>
    from barcode.codex import EAN
  File "C:\Users\riedelc\projects\zebra-printer\barcode.py", line 1, in <module>
    from barcode.codex import EAN
ModuleNotFoundError: No module named 'barcode.codex'; 'barcode' is not a package
```

## Additional

Screenshot of file tree:
![image](https://user-images.githubusercontent.com/43916661/179963329-276578ff-8b65-4c34-88e3-c1f086c3a1c2.png)
As you can see the package is installed as it should be.

**Comment by WhyNotHugo** [comment]
Is `"C:\Users\riedelc\projects\zebra-printer\` in your `$PYTHONPATH`? It seems that `import barcode` is importing your module (e.g.: `barcode.py`). So it just tries to import itself in a loop.
