### ISSUE TITLE
Pillow dreprecation warning about ImageFont.getsize

### ISSUE THREAD

**Issue by brvoisin** [WhyNotHugo/python-barcode#163]
Hello!

Pillow 9.2.0 is installed in my virtualenv and when I use python-barcode there is a deprecation warning about the method `ImageFont.getsize`.

```
virtualenv/lib/python3.9/site-packages/barcode/writer.py:441: DeprecationWarning: getsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use getbbox or getlength instead.
    width, height = font.getsize(subtext)
```

Since the version 9.2, `getsize` is deprecated and replaced by `getlength`. See the PR https://github.com/python-pillow/Pillow/pull/6381.

**Comment by WhyNotHugo** [comment]
Should we use ImageFont.getbbox or ImageFont.getlength here?

**Comment by nulano** [comment]
Author of the `font.getbbox` and `font.getlength` functions and the deprecation PR here.

This is the code in question, yes?
https://github.com/WhyNotHugo/python-barcode/blob/77c902f8b1998dbfb8c8f74ac644d5929e7846a1/barcode/writer.py#L437-L448

And it seems you are trying to align text by the bottom-middle point?
For text alignment you should use `font.getlength`, but it doesn't give you the height.
I'd suggest using `draw.text(..., anchor="ms")` instead, see [anchor documentation here](https://pillow.readthedocs.io/en/stable/handbook/text-anchors.html#text-anchors).

Perhaps (untested):
```python
 def _paint_text(self, xpos, ypos): 
     font_size = int(mm2px(pt2mm(self.font_size), self.dpi)) 
     font = ImageFont.truetype(self.font_path, font_size) 
     for subtext in self.text.split("\n"): 
         pos = ( 
             mm2px(xpos, self.dpi),
             mm2px(ypos, self.dpi),
         ) 
         self._draw.text(pos, subtext, font=font, fill=self.foreground, anchor="ms") 
         ypos += pt2mm(self.font_size) / 2 + self.text_line_distance 
```

**Comment by nulano** [comment]
In general, `getbbox` should by used for styling the text (e.g. adding a background rectangle) and `getlength` should be used for layout (word wrapping). Text alignment should now be done using anchors instead (which internally uses the same value as `getlength`).

**Comment by WhyNotHugo** [comment]
That makes sense. This deprecation is a good opportunity to polish this a bit and align text the way it _should_ be done.

@brvoisin Are you interested in writing a PR for this?

**Comment by WhyNotHugo** [comment]
Thanks for chiming in, @nulano !

**Comment by brvoisin** [comment]
> @brvoisin Are you interested in writing a PR for this?

Yes, I'll write a PR soon.

Thanks @nulano for the solution.

**Comment by cedk** [comment]
Pillow 10.0.0 has been released: https://pypi.org/project/Pillow/10.0.0/
It will be great to have a release with this fix.

**Comment by WhyNotHugo** [comment]
@cedk What fix? Pillow is unpinned, so 10.0.0 should work without any issues.

**Comment by cedk** [comment]
This [one](https://github.com/WhyNotHugo/python-barcode/pull/165) otherwise the last release of python-barcode crashes with Pillow 10.0.0.

**Comment by cedk** [comment]
For the record, our test suite is failing like this https://foss.heptapod.net/tryton/tryton/-/jobs/1990306 because the release 0.14.0 is missing this compatibility fix with Pillow 10.0.0.

**Comment by WhyNotHugo** [comment]
python-barcode 0.15.1 is out

**Comment by clevermiraz** [comment]
in new `pillow 10.0.0` version remove some method and replace.

For More Info see their Doc: [pillow documentation](https://pillow.readthedocs.io/en/stable/releasenotes/10.0.0.html)
