### ISSUE TITLE
ISBN-13 starting with 979

### ISSUE THREAD

**Issue by soyelaleph** [WhyNotHugo/python-barcode#175]
Hi. Foremost, thank you for your hard work. It is a great library.

Today I faced a problem with the new ISBN-13 979-8 prefix ( https://www.isbn-international.org/content/changes-united-states-isbn-prefixes ) that the module cannot deal with, as long as I can see.

This a valid new prefix ISBN-13: 9798786115322

The error I receive is:

`barcode.errors.BarcodeError: ISBN must start with 97910 or 97911.`

Thanks for your help.

**Comment by WhyNotHugo** [comment]
The check here needs to be updated https://github.com/WhyNotHugo/python-barcode/blob/36a11920cf32630457d926d85166dd0ce5822e42/barcode/isxn.py#L43-L51:
