### ISSUE TITLE
Pip install does not include newer releases (Ubuntu; caps at v0.7)

### ISSUE THREAD

**Issue by ryantp** [WhyNotHugo/python-barcode#18]
![screenshot from 2018-11-22 19-26-18](https://user-images.githubusercontent.com/25127589/48927670-b12abb80-ee8c-11e8-980c-c7b436882bd2.png)

> after that sweet code128

**Comment by ryantp** [comment]
nvm me, I'm tired xD

**Comment by WhyNotHugo** [comment]
lol, np
