### ISSUE TITLE
ITF-14 support required

### ISSUE THREAD

**Issue by estianross** [WhyNotHugo/python-barcode#2]
EAN14 barcode is not interchangeable with ITF-14

**Comment by violuke** [comment]
I'm not sure if it's new (since this 2108 post), but this is supported, it's just not documented https://github.com/WhyNotHugo/python-barcode/issues/154

You can use `itf` - https://github.com/WhyNotHugo/python-barcode/blob/main/barcode/itf.py

**Comment by WhyNotHugo** [comment]
Indeed, ITF has been implemented since around 2015, it was merely missing from the documentation.
