### ISSUE TITLE
dpi

### ISSUE THREAD

**Issue by bertramdryan** [WhyNotHugo/python-barcode#206]
Where is the dpi option in the ImageWriter?

**Comment by WhyNotHugo** [comment]
It is currently (regrettably) hardcoded: https://github.com/WhyNotHugo/python-barcode/blob/34e514a1ec0933cc74ee059c28d36081569e85a5/barcode/writer.py#L400-L418

A new (optional) argument to `__init__` with the default value would be acceptable.
