### ISSUE TITLE
Unexpected ">" symbol at the end of generated EAN-13 barcode

### ISSUE THREAD

**Issue by SumnanAzadi** [WhyNotHugo/python-barcode#209]
When generating an EAN-13 barcode using the python-barcode library for the barcode number 4582559574028, an unexpected ">" symbol appears at the end of the barcode image.

Steps to reproduce:
1.  Install the python-barcode library.
2. Use the EuropeanArticleNumber13WithGuard class to generate the barcode for the number 4582559574028.
3. Save and view the generated barcode image.

Expected behavior:
The generated EAN-13 barcode should represent the provided number without any extraneous symbols.

Actual behavior:
An unexpected ">" symbol appears at the end of the barcode.

Am I wrong here or missing some knowledge?

Additional context:
Here's a link to the generated barcode image that showcases the problem:
![ean13_temp_4582559574028](https://github.com/WhyNotHugo/python-barcode/assets/36268124/bf235bb1-adc9-48f3-aff3-998e9662ad1e)

**Comment by jkbz64** [comment]
Hello, I've run into the same issue, can you tell me what was the issue / how did you resolve that? Thanks

**Comment by WhyNotHugo** [comment]
Issue is gone in the latest release?

**Comment by WhyNotHugo** [comment]
Sorry, haven't had the chance to look at this one in depth.
