### ISSUE TITLE
Incompatibility with pillow 10.0.1

### ISSUE THREAD

**Issue by Nadern96** [WhyNotHugo/python-barcode#221]
```
        barcode_format = barcode.get_barcode_class('code128')
        code = barcode_format(input, writer=ImageWriter(), )
        code_path = BASE_PATH + 'code'
        path = code.save(code_path, {"font_size": font_size})
```

```
width, height = font.getsize(subtext)\nAttributeError: 'FreeTypeFont' object has no attribute 'getsize'
```

**Comment by WhyNotHugo** [comment]
What version are you using?

**Comment by richardmarktl** [comment]
The error `AttributeError: 'FreeTypeFont' object has no attribute 'getsize' occurs because Pillow 10, removed the method getsize.

**Comment by WhyNotHugo** [comment]
On Thu, 4 Apr 2024, at 11:19, richardmarktl wrote:
> 
> 
> The error `AttributeError: 'FreeTypeFont' object has no attribute 'getsize'` occurs because Pillow 10, removed the method `getsize`.
> 

Which version are you using?

**Comment by richardmarktl** [comment]
> Which version are you using?
10.3.0

**Comment by WhyNotHugo** [comment]
The latest version of this library is 0.15.1.

**Comment by WhyNotHugo** [comment]
I meant to ask which version of python-barcode, not which version or pillow.

**Comment by WhyNotHugo** [comment]
The full stack trace is also useful in these situations.

**Comment by Nadern96** [comment]
I upgraded bar-code package to 0.15.1, also upgraded pillow to 10.3.0, it seems to be working

**Comment by WhyNotHugo** [comment]
This was likely https://github.com/WhyNotHugo/python-barcode/issues/163

**Comment by richardmarktl** [comment]
exactly, thanks for your time.

Gesendet von Outlook für iOS<https://aka.ms/o0ukef>
________________________________
Von: Hugo ***@***.***>
Gesendet: Thursday, April 4, 2024 11:56:16 PM
An: WhyNotHugo/python-barcode ***@***.***>
Cc: richardmarktl ***@***.***>; Comment ***@***.***>
Betreff: Re: [WhyNotHugo/python-barcode] Incompatibility with pillow 10.0.1 (Issue #221)


This was likely https://github.com/WhyNotHugo/python-barcode/issues/163
