### ISSUE TITLE
Error on the number generated

### ISSUE THREAD

**Issue by darixsamani** [WhyNotHugo/python-barcode#222]
the number generated and the bar code is different from the one I provided to the function. I use the EAN13 standard

there are differences in last number

**Comment by WhyNotHugo** [comment]
The last digit might be the verification digit.

**Comment by WhyNotHugo** [comment]
As a minimum to understand the issue I need:

- The input value that you're providing
- The number that shows up in the barcode.

**Comment by darixsamani** [comment]
for example, i provided this input: 2024012571997
the number generated is different in the last digit

![2024012571997](https://github.com/WhyNotHugo/python-barcode/assets/67915678/c426bab1-756a-473e-973c-bf6325417677)

**Comment by darixsamani** [comment]
Hi @WhyNotHugo

**Comment by WhyNotHugo** [comment]
See: https://github.com/WhyNotHugo/python-barcode/issues/43

**Comment by darixsamani** [comment]
@WhyNotHugo Thank you I will try this solution, and I will give my feedback

**Comment by WhyNotHugo** [comment]
https://github.com/WhyNotHugo/python-barcode/pull/98 is not correct.

I believe https://github.com/WhyNotHugo/python-barcode/pull/224 should work

**Comment by darixsamani** [comment]
Please merge this pull request #224 for me to try

**Comment by darixsamani** [comment]
I tried it and it works very well.

**Comment by darixsamani** [comment]
this generates a bar code but the bar code scanner does not work
