### ISSUE TITLE
Redable text under bars is cut out from the image

### ISSUE THREAD

**Issue by santiagovassallo** [WhyNotHugo/python-barcode#225]
Hello! I'm facing this issue

![barras](https://github.com/WhyNotHugo/python-barcode/assets/18540043/c946fab7-3d09-4a39-8183-eaab4d880853)

This is the code snippet I've used

```python
import barcode
Code128 = barcode.get_barcode_class('code128')
c = Code128('04480000001240013002404300002234825000000000000512005225165')
c.save('barras')
```

The thing is, all the codes I need to create are like that, meaning they are a string of 59 chars (digits actually) long.

I tested the bars with a reader and it works, however, the human readable part is cut short.

Is there any option I may be missing to fix this?

Thanks a lot!

**Comment by WhyNotHugo** [comment]
Did you manage to work around this?

**Comment by santiagovassallo** [comment]
Yes, sorry! I should have posted how I did it when I closed this. Here it is!

```python
   ...
    encoder = barcode.get_barcode_class('code128')
    codigo_128 = encoder(codigo, writer=ImageWriter())
    buffer = BytesIO()
    codigo_128.write(buffer, options={'font_size': 6})
   ...
```

Thanks man!
