### ISSUE TITLE
I'm getting wrong barcodes

### ISSUE THREAD

**Issue by EnriqueSoria** [WhyNotHugo/python-barcode#27]
Is ist working? I'm getting wrong barcodes.

![imagen](https://user-images.githubusercontent.com/7394684/53412051-8e96ca00-39c8-11e9-8a4b-54eb658fddd4.png)

**Comment by buzzlightmonth** [comment]
I'm no barcode expert but I believe the last digit is a checksum of sorts: it is a 33 followed by a 6.

**Comment by EnriqueSoria** [comment]
> I'm no barcode expert but I believe the last digit is a checksum of sorts: it is a 33 followed by a 6.

It looks so. [Code39 mod 43 (Wikipedia)](https://en.wikipedia.org/wiki/Code_39#Code_39_mod_43)
