### ISSUE TITLE
Option to suppress check digit?

### ISSUE THREAD

**Issue by Justin-E-Taylor** [WhyNotHugo/python-barcode#29]
Is there an option to suppress the check digit?  I'm testing with the samples on the homepage, substituting in type code39, if that matters. 

TIA

**Comment by djaychela** [comment]
Hi.  I'm doing the same thing, using Code39 and didn't want the checksum in there (to suit already deployed barcodes).

You can do it using the following code to generate a code:

```
code39 = barcode.get_barcode_class('code39')

barcode_example = code39('00001', add_checksum=False, writer=ImageWriter())
```

HTH

**Comment by WhyNotHugo** [comment]
Looks like @djaychela has answered this successfully, so I'll go ahead and close this. Thanks!
