### ISSUE TITLE
Unwanted behaviour of the no_checksum option  for EuropeanArticleNumber13

### ISSUE THREAD

**Issue by mzonzon** [WhyNotHugo/python-barcode#43]
If the no_checksum option is passed, A 13 digits code should be accepted as it is.
At the moment, the last digit is replaced by a 0 and it cannot be otherwise:

```python
digits = 12
ean = ean[:self.digits]
# Add a thirteen char if given in parameter,
# otherwise pad with zero
self.ean =  '{0}{1}'.format( ean, ean[self.digits] if len(ean) > self.digits else 0)
```

`len(ean) > self.digits`  is never going to happen

**Comment by AlexP11223** [comment]
Bump.
Looks like it is indeed does not work as intended.

```
>>> barcode.get('ean13')('1234567891234', no_checksum=True)
<EuropeanArticleNumber13('1234567891230')>
```

instead of `1234567891234`.

**Comment by WhyNotHugo** [comment]
Can you confirm if #98 fixes the issue for you?

If so, I'll add some tests and merge it in. Thanks!

**Comment by AlexP11223** [comment]
I am too lazy to figure out how to build/install it :D

But yeah, looks correct.

Maybe adding some validation for the number of digits would be good.

> Fix crash

hm, I did not have any crashes. :thinking:
