### ISSUE TITLE
TypeError running commandline example

### ISSUE THREAD

**Issue by guxi798** [WhyNotHugo/python-barcode#45]
Running Python 3.6.5. I tested the command-line example with ended with the following error.
`python-barcode create "My Text" outfile`

```
Traceback (most recent call last):
  File "/anaconda3/bin/python-barcode", line 10, in <module>
    sys.exit(main())
  File "/anaconda3/lib/python3.6/site-packages/barcode/pybarcode.py", line 119, in main
    func(args, parser)
  File "/anaconda3/lib/python3.6/site-packages/barcode/pybarcode.py", line 63, in create_barcode
    args.text)
  File "/anaconda3/lib/python3.6/site-packages/barcode/__init__.py", line 73, in generate
    barcode = get(name, code, writer, options)
  File "/anaconda3/lib/python3.6/site-packages/barcode/__init__.py", line 61, in get
    return barcode(code, writer, **options)
TypeError: __init__() got an unexpected keyword argument 'compress'
```

Any suggestions?

**Comment by jay51** [comment]
Hey @guxi798, The example in the docs is not how you should actually run `python-barcode`. It's misleading and should be updated. However This is issue is a bug that needs to be fixed.
This is how you should run it. 

`python-barcode create "123456789000" outfile.png -b ean --text "text to appear under barcode" `

**Comment by jay51** [comment]
just a little typo, `outfile.png` should be just `outfile`. I believe by default, the image should be svg

**Comment by tokt** [comment]
Hello,
I have same problem if I try to generate code128 barcodes: "python-barcode create "123456789000" outfile1 -b code128" fails with above error, while "python-barcode create "123456789000" outfile2 -b ean" works perfectly. This is on freshly installed CentOS7 qcow2 image.
commands to reproduce:
- yum update -y
- yum install python3-pip -y
- pip3 install python-barcode
-  python-barcode create "123456789000" outfile1 -b code128 // this will fail.

**Comment by WhyNotHugo** [comment]
Fixed.
