### ISSUE TITLE
can not install it in win10 or centos7

### ISSUE THREAD

**Issue by bbg221** [WhyNotHugo/python-barcode#52]
I download the code from the trunk line and install it  with 'python setup.py install'  into my win10 and centos7.  all of them are failed.
 "ImportError: No module named pathlib" is occurred first, after I fix it by 'pip install pathlib',  

```
Traceback (most recent call last):
  File ".\setup.py", line 17, in <module>
    long_description=Path('README.rst').read_text(),
AttributeError: 'WindowsPath' object has no attribute 'read_text'
```  
occurred in windows  and 

```
Traceback (most recent call last):
  File "setup.py", line 17, in <module>
    long_description=Path('README.rst').read_text(),
AttributeError: 'PosixPath' object has no attribute 'read_text'
```
occurred in centos7.

**Comment by WhyNotHugo** [comment]
`pathlib` is part of python itself, but only exists as of python 3.4.

You're probably using a very old python (3.3?) which we don't support. What's the output of `python --versión`.
