### ISSUE TITLE
Inline svg does not need the doctype

### ISSUE THREAD

**Issue by Azd325** [WhyNotHugo/python-barcode#60]
If you use the svg output as inline svg in html the doctype declaration is not needed and could lead to problems.

https://stackoverflow.com/a/38172170/548558

**Comment by WhyNotHugo** [comment]
Seems like a pretty valid/usual usecase.

Probably adding an optional param `with_doctype=True` to `SVGWriter`'s constructor would be the cleanest way to go about this.

I'd happily merge any PRs that do this -- or I'll try to address it when I get a change at some point, not probably not soon.
