### ISSUE TITLE
UnboundLocalError: local variable 'barcode' referenced before assignment

### ISSUE THREAD

**Issue by xuanduy1508** [WhyNotHugo/python-barcode#62]
![image](https://user-images.githubusercontent.com/61442900/75210783-ab6d0580-57b4-11ea-9718-9bb93cf2effb.png)
help me pls. thanks.

**Comment by heuer** [comment]
Try to rename your factory function ``barcode`` into ``make_barcode``  / ``create_barcode``

I guess you're suffering from name conflicts (function name == package name)

**Comment by WhyNotHugo** [comment]
Do you have a variable called `barcode` inside that scope? It would seem to be shadowing the imported `barcode`.
