### ISSUE TITLE
Unable to import barcode

### ISSUE THREAD

**Issue by Soumalya-Mondal** [WhyNotHugo/python-barcode#63]
i already install barcode module from official python site like "pip install python-barcode". but whenever i write a code on text editor like 1-Visual Studio 2-SubLime 3-Pycharm theirs an error pop up and it's says "Unable to import 'barcode' pylint(input-error)[1,1]"

**Comment by WhyNotHugo** [comment]
No idea what to say here. I haven't used any of the tools you mention, but it would seem they're using a different python.

I expect that you'll get this error for any library you install, right?

**Comment by WhyNotHugo** [comment]
Can you do the following:
- On you editor, run this code and what does it output? `import sys; sys.path` 
- On the same console you ran `pip install`, what does this output? `python -c "import sys; print(sys.path)"` And this? `pip --version`?

This should help figure out if they're using different pythons.

**Comment by mrshin0212** [comment]
I got same problem.
ModuleNotFoundError: No module named 'barcode.writer'; 'barcode' is not a package
But it's working fine only on this folder: C:\Program Files\Python38\Lib\site-packages\tests
Can you help me fix this problem.
===========
Folder: C:\Program Files\Python38\Lib\site-packages\barcode
pip 20.2b1 from c:\program files\python38\lib\site-packages\pip-20.2b1-py3.8.egg\pip (python 3.8)
--
Print(sys.path)
['D:\\GG\\1.Hung\\My Code\\Pro1', 'C:\\Program Files\\Python38\\python38.zip', 'C:\\Program Files\\Python38\\DLLs', 'C:\\Program Files\\Python38\\lib', 'C:\\Program Files\\Python38', 'C:\\Users\\Mr Shin Heo\\AppData\\Roaming\\Python\\Python38\\site-packages', 'C:\\Program Files\\Python38\\lib\\site-packages', 'C:\\Program Files\\Python38\\lib\\site-packages\\pip-20.2b1-py3.8.egg', 'C:\\Program Files\\Python38\\lib\\site-packages\\win32', 'C:\\Program Files\\Python38\\lib\\site-packages\\win32\\lib', 'C:\\Program Files\\Python38\\lib\\site-packages\\Pythonwin']
---
python -c "import sys; print(sys.path)"
['', 'C:\\Program Files\\Python38\\python38.zip', 'C:\\Program Files\\Python38\\DLLs', 'C:\\Program Files\\Python38\\lib', 'C:\\Program Files\\Python38', 'C:\\Users\\Mr Shin Heo\\AppData\\Roaming\\Python\\Python38\\site-packages', 'C:\\Program Files\\Python38\\lib\\site-packages', 'C:\\Program Files\\Python38\\lib\\site-packages\\pip-20.2b1-py3.8.egg', 'C:\\Program Files\\Python38\\lib\\site-packages\\win32', 'C:\\Program Files\\Python38\\lib\\site-packages\\win32\\lib', 'C:\\Program Files\\Python38\\lib\\site-packages\\Pythonwin']
----

**Comment by WhyNotHugo** [comment]
I've no idea how Python works on windows, but it seems that when you ran `print(sys.path)`, the list of directories where python searches for packages had an extra entry (the first one) compared to  when you did `python -c "import sys; print(sys.path)"`.

This indicates that the environment for both runs is different.

How did you run `python` when you ran `print(sys.path)`? Via an IDE? Is this where importing `barcode` _does_ work?

**Comment by mrshin0212** [comment]
I found a solution: copy Tests folder from here : `C:\Program Files\Python38\Lib\site-packages\tests` 
And create new file .py on this folder: Barcode is working fine. 
![Screenshot_11](https://user-images.githubusercontent.com/64638164/82721887-def3f900-9ceb-11ea-8d6f-3abd0e8c6c8d.png)

**Comment by WhyNotHugo** [comment]
I've no idea why that works for you or how your setup is laid out, but happy it works for you. I suspect you either have two pythons, or two different environment configurations somewhere.

Glad you figured it out.

**Comment by eadmaster** [comment]
for me this was due to a name clash with [this module](https://pypi.org/project/barcode/).
Solution:
````
pip uninstall barcode
pip install python-barcode
````

**Comment by enter360** [comment]
> for me this was due to a name clash with [this module](https://pypi.org/project/barcode/). Solution:
> 
> ```
> pip uninstall barcode
> pip install python-barcode
> ```

Intellij automatically installed the shorter named library for me. This fix worked for me as well.

**Comment by WhyNotHugo** [comment]
Odd. The `barcode` package had been abandoned for years, hence this fork. Looks like there's a new package published under that name now.

**Comment by shahrozhassan** [comment]
this is absolutely working and hopefully it will resolve your issue
pip uninstall barcode
pip install python-barcode

**Comment by sahad-cp** [comment]
this are not working. please help me

**Comment by WhyNotHugo** [comment]
@sahad-cp Nobody can help if you don't describe your problem. Please open a new issue and explain what's not working and what you've tried.

**Comment by mumanye** [comment]
> this are not working. please help me

make sure your python file is also not called barcode.py that can also cause a conflict. Hope that helps

**Comment by pmcgaley** [comment]
> make sure your python file is also not called barcode.py that can also cause a conflict. Hope that helps
and that you don't have _any_ `barcode.py` in the same directory, same reason
