### ISSUE TITLE
barcode.get  writer_options not used

### ISSUE THREAD

**Issue by karna48** [WhyNotHugo/python-barcode#68]
def get(name, code=None, writer=None, options=None, writer_options=None):

does not pass writer_options anywhere and the documentation does not speak about it

**Comment by WhyNotHugo** [comment]
Sounds like it can be dropped, thanks for pointing it out!
Interested in sending a PR for that?

**Comment by karna48** [comment]
Hello, sorry, I do not feel like doing that.
Best regards,
LD

Dne ne 3. 5. 2020 20:28 uživatel Hugo Barrera <notifications@github.com>
napsal:
