### ISSUE TITLE
EAN-13 barcode numbers position and grouping 

### ISSUE THREAD

**Issue by hazardland** [WhyNotHugo/python-barcode#74]
Is it possible somehow that numbers could be positioned like on the image?

![image](https://user-images.githubusercontent.com/2015121/82461258-42eba700-9acb-11ea-964e-c7eb49fc373c.png)

**Comment by WhyNotHugo** [comment]
Hmm... No, not out of the box. Is this some "standard" positioning format?

**Comment by SkymaxPlay** [comment]
Yes, it is standard positioning format

**Comment by WhyNotHugo** [comment]
There seems to be some custom positioning on the GS1's website, but it doesn't match the alignment from your image.

Can you like to the spec that defines this standard? I might have a look at it, but it seems a bit non-trivial.

**Comment by hazardland** [comment]
I had to switch on https://pypi.org/project/treepoem/ it seems that kind of positioning is not mandatory but is industry defined. In any case clients are happy.

But treepoem needs ghostscript and depends on other libraries a lot and it results huge docker images.

**Comment by WhyNotHugo** [comment]
Do you have any example of a tool that fails to read one and not the other?

Given how barcodes work, this looks like an aesthetic choice, rather than something technical.

**Comment by SkymaxPlay** [comment]
YES, from the beginning we talking about esthetic aspect only

**Comment by TensorTom** [comment]
I also came here looking for this kind of spacing. Now I just want the option to remove the text so I can do it manually. A lot of us are probably needing to add barcode generatation to our clients' software. They will give us an example and then when ours doesn't look the same they will say "It looks better the first way. Can you make it?" To which I'll reply "It shall be so" before I even perform my first search.

**Comment by WhyNotHugo** [comment]
> As for extending the lines, that shouldn't be too hard of a contribution. I'm surprised that this wasn't considered from the start. These extended lines and text positioning are ubiquitous.

I've never personally seen them in real life, nor have any clients/jobs ever required them. It seems that nobody interested in them has been interested enough to bother implementing it. :shrug: 

Happy to accept PRs that implement these change behind some flag though, I've no objection to them.
