### ISSUE TITLE
Using 'raw' without using 'save' gives no output

### ISSUE THREAD

**Issue by sharifanani** [WhyNotHugo/python-barcode#8]
I think the title explains it all.

If I try to use .raw to server an SVG barcode without using .save first, I get an empty output...

Example:
Trying to serve this in my django project:

```
class APIBarcode(View):

    def get(self, request, *args, **kwargs):
        uuid = request.GET.get('uuid')
        C39 = barcode.get_barcode_class('code39')
        toserve = C39(uuid)
        toserve.save('c39code')
        return HttpResponse(toserve.raw, content_type="image/svg+xml")
```

Gives the following output:
![image](https://user-images.githubusercontent.com/11825589/40337929-a858c8a6-5d2f-11e8-891b-fa7ecdcf632c.png)

But serving this:
```
class APIBarcode(View):

    def get(self, request, *args, **kwargs):
        uuid = request.GET.get('uuid')
        C39 = barcode.get_barcode_class('code39')
        toserve = C39(uuid)
        # toserve.save('c39code')
        return HttpResponse(toserve.raw, content_type="image/svg+xml")
```
Gives the following output:

![image](https://user-images.githubusercontent.com/11825589/40337973-e869d9e4-5d2f-11e8-9045-3b01c3cee5d2.png)

If someone can point me to where I should be looking I would gladly attempt to fix it!

**Comment by WhyNotHugo** [comment]
You probably want the `render` method, rather than `raw`:

```
def get(self, request, *args, **kwargs):
    uuid = request.GET.get('uuid')
    C39 = barcode.get_barcode_class('code39')
    toserve = C39(uuid)
    return HttpResponse(toserve.render(), content_type="image/svg+xml")`
```

**Comment by sharifanani** [comment]
@WhyNotHugo `.render()` method needs a positional argument (which I did not get how to specify from the docs), `.render` attribute gives the same empty result as I showed previously

**Comment by WhyNotHugo** [comment]
`raw` is actually an ugly side effect of poor code (it's actually removed in the latest master, and was actually buggy).

I'm thinking about reintroducing a `raw` property, which returns the raw barcode properly (rather than write it) for situations like this.

**Comment by sharifanani** [comment]
I can take a shot at that if you'd like!

**Comment by WhyNotHugo** [comment]
Give it a shot if you like; it'll be a while before I can address this myself.

**Comment by WhyNotHugo** [comment]
Given that `render` already returns the rendered barcode, and seems to suffer no limitations, I think it's okay to close this.

Don't hesitate to leave a reply if you consider there's something I might have overlooked here.
