### ISSUE TITLE
generate wrong number 

### ISSUE THREAD

**Issue by MRTUNC** [WhyNotHugo/python-barcode#80]
This module is usefull and easy.thanks  developer.
But ı have got  a problem that generate wrong number
here is my code:

```python
from barcode import EAN13
import barcode
from barcode.writer import ImageWriter

serino="1234567891012"
dosyaadi=str(serino)+".jpg"
with open(dosyaadi, 'wb') as f:
    EAN13(str(serino), writer=ImageWriter()).write(f)
```

![image](https://user-images.githubusercontent.com/42121592/88299652-4558c000-cd0b-11ea-829c-6f2d52901288.png)

 As you see ;
last caracter is not true;
I have tried too much but ı cant ;
Would you please help me  ?
What is wrong ?

**Comment by WhyNotHugo** [comment]
The 13th digit in EAN barcodes is a checksum/verification digit.
Looks like the `2` you provide is stripped away (we probably should log a warning here), and the right digit is calculated.

`9` seems to be the right value in this case, I double check with [this tool](https://www.gs1.org/services/check-digit-calculator).
