### ISSUE TITLE
Proposal: Replace pyBarcode with your project at awesome-python

### ISSUE THREAD

**Issue by heuer** [WhyNotHugo/python-barcode#89]
Not a bug, just a proposal ;)

https://github.com/vinta/awesome-python#image-processing lists the unmaintained pyBarcode project, Maybe it would make sense to open an issue an suggest to list python-barcode instead.

**Comment by WhyNotHugo** [comment]
Appreciate the hint. I've addressed it in https://github.com/vinta/awesome-python/pull/1606.
