### ISSUE TITLE
viivakoodi causes problem writing image

### ISSUE THREAD

**Issue by geftactics** [WhyNotHugo/python-barcode#95]
I am trying to use python-barcode to generate images to print via python-escpos. The following code works...

```
import barcode
import io
from barcode import Code128

barcode_data = 'S2000000fb9ec99718'
barcode_img = io.BytesIO()
writer = barcode.writer.ImageWriter()
b = Code128(barcode_data, writer=barcode.writer.ImageWriter())
b.write(barcode_img)
```

The latest version of python-escpos installs viivakoodi-0.8.0 - once this is present, I get the following error when I try and write the barcode to my BytesIO:
```
Traceback (most recent call last):
  File "./print.py", line 9, in <module>
    b.write(barcode_img)
  File "<SNIP>/venv/lib/python3.8/site-packages/barcode/base.py", line 85, in write
    fp.write(output)
TypeError: a bytes-like object is required, not 'Image'
```

**Comment by WhyNotHugo** [comment]
Looking at `viivakoodi`, it seems installing it would overwrite this library. Try reinstalling this library _after_ that other one.

`viivakoodi` hasn't been updated in over 3 years. You might want to recommend to the python-escpos devs that they use this as a dependency instead.

**Comment by geftactics** [comment]
You're right... a `pip3 install --force-reinstall python-barcode==0.13.1` brought things back to life.

I shall raise this with `python-escpos`...

**Comment by geftactics** [comment]
Looks like they already did this in 3.0a8!

**Comment by WhyNotHugo** [comment]
Neat! Glad it worked.
