### ISSUE TITLE
always the same barcode is generated

### ISSUE THREAD

**Issue by vincesdf** [WhyNotHugo/python-barcode#97]
With this code, the generated pdf contains many repetition of the same barcode but there is only different string code in the "codes" variable.
[barcodes.pdf](https://github.com/WhyNotHugo/python-barcode/files/5609790/barcodes.pdf)

`def generatePDF2(codes):
            from reportlab.graphics.barcode import eanbc
            from reportlab.graphics.shapes import Drawing 
            from reportlab.lib.pagesizes import A4
            c = canvas.Canvas("barcodes.pdf", pagesize=A4)
            pageWidth, pageHeight = A4
            for i,code in enumerate(codes):
                reload(eanbc)
                barcode_eanbc13 = eanbc.Ean13BarcodeWidget(code)
                bounds = barcode_eanbc13.getBounds()
                width = bounds[2] - bounds[0]
                height = bounds[3] - bounds[1]
                d = Drawing(50, 10)
                d.add(barcode_eanbc13)
                renderPDF.draw(d, c, width*i%pageWidth, height* (width*i/pageWidth))
            c.save()`

**Comment by WhyNotHugo** [comment]
Surround your code in three backticks to format properly

This:
    ```python
    def generatePDF2(codes):
        from reportlab.graphics.barcode import eanbc
        from reportlab.graphics.shapes import Drawing 
        from reportlab.lib.pagesizes import A4
        c = canvas.Canvas("barcodes.pdf", pagesize=A4)
        pageWidth, pageHeight = A4
        for i,code in enumerate(codes):
            reload(eanbc)
            barcode_eanbc13 = eanbc.Ean13BarcodeWidget(code)
            bounds = barcode_eanbc13.getBounds()
            width = bounds[2] - bounds[0]
            height = bounds[3] - bounds[1]
            d = Drawing(50, 10)
            d.add(barcode_eanbc13)
            renderPDF.draw(d, c, width*i%pageWidth, height* (width*i/pageWidth))
        c.save()
    ```

Renders this:

```python
def generatePDF2(codes):
    from reportlab.graphics.barcode import eanbc
    from reportlab.graphics.shapes import Drawing 
    from reportlab.lib.pagesizes import A4
    c = canvas.Canvas("barcodes.pdf", pagesize=A4)
    pageWidth, pageHeight = A4
    for i,code in enumerate(codes):
        reload(eanbc)
        barcode_eanbc13 = eanbc.Ean13BarcodeWidget(code)
        bounds = barcode_eanbc13.getBounds()
        width = bounds[2] - bounds[0]
        height = bounds[3] - bounds[1]
        d = Drawing(50, 10)
        d.add(barcode_eanbc13)
        renderPDF.draw(d, c, width*i%pageWidth, height* (width*i/pageWidth))
    c.save()
```

That said, wrong library:
```python
from reportlab.graphics.barcode import eanbc
#    ^ This is another library.
```
